version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - D:/lucasrmagalhaes/bootcamp_eduzz-node_react/_volumes/mysql/data:/var/lib/mysql
      - D:/lucasrmagalhaes/bootcamp_eduzz-node_react/_volumes/mysql/conf.d:/etc/mysql/conf.d
      ## - D:/Eduzz/Mentoria DIO/mentoria-live/mentoria-dio/_volumes/mysql/data:/var/lib/mysql
      ## - D:/Eduzz/Mentoria DIO/mentoria-live/mentoria-dio/_volumes/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports: 
      - 15672:15672
      - 5672:5672